unique_name: Product Dimension
object_type: dimension
label: Product Dimension
calculation_groups:
  - unique_name: Total Percent
    label: Total Percent
    description: Total Percent
    calculated_members:
      - unique_name: Product Dimension Pct of Total
        description: Pct of Total
        expression: >-
          ([Product Dimension].[Product Dimension].CurrentMember,
          [Measures].currentMember) / ([Product Dimension].[Product
          Dimension].[All], [Measures].currentMember)
        format: Percent
      - unique_name: Current
        description: The measure's value for the current dimension members in the query.
        expression: >-
          ([Product Dimension].[Product Dimension].CurrentMember,
          [Measures].currentMember)
        format: Standard
      - unique_name: Product Dimension Pct of Parent
        description: Pct of Parent
        expression: >-
          ([Product Dimension].[Product Dimension].CurrentMember,
          [Measures].currentMember) / ([Product Dimension].[Product
          Dimension].CurrentMember.parent, [Measures].currentMember)
        format: Percent
    folder: Total Percent
hierarchies:
  - unique_name: Product Dimension
    label: Product Dimension
    filter_empty: 'yes'
    folder: Product Attributes
    levels:
      - unique_name: Product Category
      - unique_name: Product Class
      - unique_name: Product Brand
      - unique_name: Product Item
        secondary_attributes:
          - unique_name: Product Color
            label: Product Color
            dataset: item
            folder: Product Attributes
            key_columns:
              - I_COLOR
            name_column: I_COLOR
            sort_column: I_COLOR
          - unique_name: Product Description
            label: Product Description
            contains_unique_names: false
            dataset: item
            is_unique_key: false
            key_columns:
              - I_ITEM_SK
            name_column: I_ITEM_DESC
level_attributes:
  - unique_name: Product Category
    label: Product Category
    dataset: item
    key_columns:
      - I_CATEGORY
    name_column: I_CATEGORY
  - unique_name: Product Brand
    label: Product Brand
    dataset: item
    key_columns:
      - I_BRAND
      - I_CATEGORY
      - I_CLASS
    name_column: I_BRAND
  - unique_name: Product Class
    label: Product Class
    dataset: item
    key_columns:
      - I_CLASS
      - I_CATEGORY
    name_column: I_CLASS
  - unique_name: Product Item
    label: Product Item
    dataset: item
    is_unique_key: true
    key_columns:
      - I_ITEM_SK
    name_column: I_PRODUCT_NAME
modeler_metadata:
  version: '0'
  modified: 'false'
type: standard
